spring.application.name=Blogging-App
server.port=${PORT:9292}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/blog_app}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Root}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

project.image=images/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework=INFO

jwt.secret=${JWT_SECRET_KEY:your-local-secret-key-must-be-at-least-32-characters-long}